baseURL: https://iamlow.github.io/artepiano/
languageCode: en-us
title: Arte Piano
theme: hugo-fresh

params:
  navbarlogo:
  # Logo (from static/images/logos/___)
   image: logos/footer.png
   link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: 아르테 피아노 조율.
    # Hero subtitle (optional)
    # subtitle: 모차르트와 베토벤을 사랑하며, 음악이 주는 영혼의 소리를 좋아합니다.
    subtitle: 다년간의 경험을 바탕으로 최선을 다하고 있습니다. 조율상담 환영!
    # Button text
    buttontext: 최현철 (국가공인1급 Piano Tuner)
    # Where the main hero button links to
    # buttonlink: "#"
    # Hero image (from static/images/___)
    image: illustrations/title.jpg
    # Footer logos (from static/images/logos/clients/___.svg)
    # clientlogos:
    # - systek
    # - tribe
    # - kromo
    # - infinite
    # - gutwork
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  # navbar:
  # - title: Features
  #   url: /
  # - title: Pricing
  #   url: /
  # - title: Dropdown
  #   sublinks:
  #   - title: Dropdown item
  #     url: /
  #   - title: Dropdown item
  #     url: /
  #   - title: Dropdown item
  #     url: /
  # - title: Log in
  #   url: /
  # - title: Sign up
  #   url: /
  #   button: true
  # section1:
  #   title: 주요 작업 경력
  #   subtitle: 
  #   tiles:
  #   - title: 조율(T)
  #     icon: mouse-globe
  #     text: 음율을 정확하게 맞춤
  #     url: /
  #     buttonText: Tuning
  #   - title: 조정(F)
  #     icon: laptop-cloud
  #     text: 피아노의 탄력성을 맞춤
  #     url: /
  #     buttonText: Function
  #   - title: 정음(T)
  #     icon: plug-cloud
  #     text: 음색을 균형있게 작업
  #     url: /
  #     buttonText: True Sound

  section2:
    title: 주요 작업 경력 
    # subtitle:
    features:
    - title: 총신대학교, 대학원 (피아노과) / 계원예술고등학교
      # text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
      # Icon (from /images/illustrations/icons/___.svg)
      icon: school
    - title: 교회 / 학원 / 개인 피아노 
      text: 조율 출장 전문
      icon: home-solid
    - title: 피아노 조율 자격 시험 지도
      text: 피아노 조율 기능사 및 1급 산업기사 자격증을 원하시는 분은 1:1 지도하오니 연락바랍니다. (필기, 실기 과정; 3개월, 6개월 코스)
      icon: license

  # section3:
  #   title: One platform
  #   subtitle: To rule them all
  #   image: illustrations/mockups/app-mockup.png
  #   buttonText: Get started
  #   buttonLink: "#"
  section4:
    title: Arte Piano T.F.T
    subtitle: 조율, 조정, 정음은 전체의 환경을 유기적으로 연관 시켜 작업
    clients:
    - name: 조율(Tuning) 
      quote: 현 하나는 평균 80~90kg. 전체로는 약 20톤의 장력으로 당겨져 있습니다. 현을 감고 있는 튜닝핀을 튜닝헤머로 회전 조절하여 약 240개의 음율을 맞춥니다.
      job: 음율을 정확하게 맞춤
      img: 1
    - name: 조정(Function)
      quote: 액션(Action)의 미세한 조정을 통해 탄력이 좋은 터치를 만드는 작업입니다. 액션부의 움직임과 건반의 높이와 깊이를 조정하여 88건반의 균형을 맞춥니다.
      job: 피아노의 탄력성을 맞춤
      img: 2
    - name: 정음(Truesound)
      quote: 전체 균형을 고려하면서 헤머에 보이싱 작업을 하여 벨트의 탄력을 조정해서 소리의 울림을 조절하여 아름답고 균형있는 음색을 만드는 중요한 작업입니다.
      job: 음색을 균형있게 작업
      img: 3
  section5: false
  footer:
    # Logo (from /images/logos/___)
    logo: footer.png
    # Social media links (GitHub, Twitter, etc.). All are optional.
    # socialmedia:
    # - link: https://iamlow.github.io/artepiano
    #   # Icons are from Font Awesome
    #   icon: github
    # # - link: https://dribbble.com/#
    # #   icon: dribbble
    # - link: https://facebook.com/#
    #   icon: facebook
    # - link: https://twitter.com/lucperkins
    #   icon: twitter
    # - link: https://bitbucket.org/#
    #   icon: bitbucket
    bulmalogo: false
    quicklinks:
      column1:
        title: "Contact"
        links:
        - text: hp; 010.5049.4823
          link: #
        - text: tel; 031.701.4823
          # link: /
        - text: fax; 031.701.4823
          # link: /
        - text: email; choi5558@hanmail.net
          # link: /
        # - text: AGB
        #   link: /agb
      # column2:
      #   title: "Docs"
      #   links:
      #   - text: Get started
      #     link: /
      #   - text: User guides
      #     link: /
      #   - text: Admin guide
      #     link: /
      #   - text: Developers
      #     link: /
      # column3:
      #   title: "Blog"
      #   links:
      #   - text: Latest news
      #     link: /blog/first
      #   - text: Tech articles
      #     link: /blog/second
